### ISSUE TITLE
Android 12 Beta 3 Boot Loop Issue

### ISSUE THREAD

**Issue by AYAN98542** [ruhend/Gboard-New-UI#3]
It doesn't work on beta 3!

**Comment by ruhend** [comment]
Yeah, I've taken a note on it.
Boot loops after flashing the zip.
I'll patch it ASAP

Thank you @AYAN98542

**Comment by ruhend** [comment]
Support is now added. 
Changes are pushing into master branch
[PR#4](https://github.com/ruhend/Gboard-New-UI/pull/4)
